import type { Metadata } from "next";
import { 
  Geist,
  Geist_Mono,
  Amatic_SC,
  Zen_Kurenaido,
  Funnel_Display,
  Klee_One,
  Lexend,
  Noto_Serif_Georgian,
  Outfit,
  Noto_Sans_JP
} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

// Load Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const amaticSC = Amatic_SC({
  variable: "--font-amatic-sc",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const zenKurenaido = Zen_Kurenaido({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  style: ["normal"],
  variable: "--font-zen-kurenaido",
});

const notoSansJP = Noto_Sans_JP({
  weight: ["900"],
  subsets: ["latin"],
  display: "swap",
  style: ["normal"],
  variable: "--font-noto-sans-jp",
});

const lexend = Lexend({
  weight: ['400', '700'],
  style: ['normal'],
  variable: '--font-lexend', 
  subsets: ['latin'],
});

const kleeOne = Klee_One({
  weight: ['400'], // Or specify the desired weights/styles
  subsets: ['latin'],
  variable: '--font-kleen-one',
  display: "swap",
});

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  weight: ["700"],
  subsets: ["latin"],
  display: "swap",
});

const notoSerifGeorgian = Noto_Serif_Georgian({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal"],
  variable: "--font-noto-serif-georgian",
  display: 'swap',
});

const outfit = Outfit({
  weight: ['400', '700'],
  subsets: ['latin'],
  style: ["normal"],
  display: 'swap',
  variable: "--font-outfit",
});

// Metadata
export const metadata: Metadata = {
  icons: "/images/ben.png",
  title: "Ben Kyokai",
  description: "Generated by create next app",
};

// Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${amaticSC.variable} 
          ${zenKurenaido.variable}
          ${kleeOne.variable}
          ${lexend.variable}
          ${funnelDisplay.variable}
          ${notoSerifGeorgian.variable}
          ${outfit.variable}
          ${notoSansJP.variable}
          antialiased
        `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
