type ArticlePancakeDataType = {
  title: string;
  tags: {en: string, jp: string}[];
  content: string;
}
export const PancakeData: ArticlePancakeDataType[] = [
  {title: "Quantum Pancakes (January 31st, 2025)", tags: [{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"}], content: "In a surprising turn of culinary innovation, quantum pancakes have taken the breakfast world by storm. Unlike traditional pancakes, which are confined to the plate, quantum pancakes exist in a superposition of states, both cooked and uncooked, until observed. This phenomenon, described as “fluffy uncertainty,” has baffled physicists and chefs alike. “The batter somehow folds itself into 11-dimensional layers,” said Dr. Maple Syrupstein, lead researcher at the Institute of Theoretical Brunch Studies. “Each bite is simultaneously sweet, savory, and tangy, depending on the eater’s mood.”<a class='text-[#B45F06] underline'>Continue Reading</a>"},
  {title: "Quantum Pancakes (January 31st, 2025)", tags: [{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"}], content: "In a surprising turn of culinary innovation, quantum pancakes have taken the breakfast world by storm. Unlike traditional pancakes, which are confined to the plate, quantum pancakes exist in a superposition of states, both cooked and uncooked, until observed. This phenomenon, described as “fluffy uncertainty,” has baffled physicists and chefs alike. “The batter somehow folds itself into 11-dimensional layers,” said Dr. Maple Syrupstein, lead researcher at the Institute of Theoretical Brunch Studies. “Each bite is simultaneously sweet, savory, and tangy, depending on the eater’s mood.”<a class='text-[#B45F06] underline'>Continue Reading</a>"},
  {title: "Quantum Pancakes (January 31st, 2025)", tags: [{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"}], content: "In a surprising turn of culinary innovation, quantum pancakes have taken the breakfast world by storm. Unlike traditional pancakes, which are confined to the plate, quantum pancakes exist in a superposition of states, both cooked and uncooked, until observed. This phenomenon, described as “fluffy uncertainty,” has baffled physicists and chefs alike. “The batter somehow folds itself into 11-dimensional layers,” said Dr. Maple Syrupstein, lead researcher at the Institute of Theoretical Brunch Studies. “Each bite is simultaneously sweet, savory, and tangy, depending on the eater’s mood.”<a class='text-[#B45F06] underline'>Continue Reading</a>"},
  {title: "Quantum Pancakes (January 31st, 2025)", tags: [{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"}], content: "In a surprising turn of culinary innovation, quantum pancakes have taken the breakfast world by storm. Unlike traditional pancakes, which are confined to the plate, quantum pancakes exist in a superposition of states, both cooked and uncooked, until observed. This phenomenon, described as “fluffy uncertainty,” has baffled physicists and chefs alike. “The batter somehow folds itself into 11-dimensional layers,” said Dr. Maple Syrupstein, lead researcher at the Institute of Theoretical Brunch Studies. “Each bite is simultaneously sweet, savory, and tangy, depending on the eater’s mood.”<a class='text-[#B45F06] underline'>Continue Reading</a>"},
  {title: "Quantum Pancakes (January 31st, 2025)", tags: [{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"}], content: "In a surprising turn of culinary innovation, quantum pancakes have taken the breakfast world by storm. Unlike traditional pancakes, which are confined to the plate, quantum pancakes exist in a superposition of states, both cooked and uncooked, until observed. This phenomenon, described as “fluffy uncertainty,” has baffled physicists and chefs alike. “The batter somehow folds itself into 11-dimensional layers,” said Dr. Maple Syrupstein, lead researcher at the Institute of Theoretical Brunch Studies. “Each bite is simultaneously sweet, savory, and tangy, depending on the eater’s mood.”<a class='text-[#B45F06] underline'>Continue Reading</a>"},
  {title: "Quantum Pancakes (January 31st, 2025)", tags: [{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"},{en:"TAG", jp:"タグ"}], content: "In a surprising turn of culinary innovation, quantum pancakes have taken the breakfast world by storm. Unlike traditional pancakes, which are confined to the plate, quantum pancakes exist in a superposition of states, both cooked and uncooked, until observed. This phenomenon, described as “fluffy uncertainty,” has baffled physicists and chefs alike. “The batter somehow folds itself into 11-dimensional layers,” said Dr. Maple Syrupstein, lead researcher at the Institute of Theoretical Brunch Studies. “Each bite is simultaneously sweet, savory, and tangy, depending on the eater’s mood.”<a class='text-[#B45F06] underline'>Continue Reading</a>"},
]